### ISSUE TITLE
Look so small I hope look more bigger(运行后看起来太小了 希望看起来大一些)

### ISSUE THREAD

**Issue by jiangshantao** [rgbkrk/atom-script#1508]
<img width="569" alt="2017-12-30 11 09 47" src="https://user-images.githubusercontent.com/25195806/34455276-8d31e42e-edb6-11e7-88db-a5042952d6ba.png">

**Comment by tweakimp** [comment]
If you want to make the output bigger:
Go to: Settings > Open Config folder > .atom\packages\script\styles\script.less

Change:
```less
.script-view {
  .panel-body pre {
    background: @tool-panel-background-color;
    color: @text-color;
  }
```
To:
```less
.script-view {
  .panel-body pre {
    background: @tool-panel-background-color;
    color: @text-color;
    font-size: 12px; # << or any other size you want
  }
```
